pipeline {
    agent any
    stages {
        stage('test') {
            agent {
                docker {
                    image 'node:16.17.0'
                    reuseNode true
                }
            }
            environment {
                 HOME = '.'
            }
            steps {
                sh 'npm install'
                sh 'npm run jenkinsTest'
            }
        }
    }
}