pipeline {
    agent any
    stages {
        stage('createDist') {
            agent {
                docker {
                    image 'node:10'
                    reuseNode true
                }
            }
            steps {
                sh 'npm install'
                sh 'npm run build:prod'
            }
        }
        // stage('uploadToServer') {
        //     steps {
        //         // sh 'rsync -avzd -e ssh dist/* '
        //     }
        // }
    }
}